# DSA_With_Java
- Introduction
- Operators
- Conditional Statements
- About loops
- Patterns
- Arrays
- 2D-Arrays
- String
- Two Pointer Technique
- Sliding Windows
- Sorting Algorithms
- Oop's Concepts
- Time and Space Complexity
- Recursion
- Backtracking
- Stack
- Queues
- ArraysList
- LinkedLists
- Bit Manipulations
- Divide and Conquer
- Greedy Algorithms
- Binary Trees
- Binary Search Trees
- Hashing
- Heaps
- Tries
- Graphs
- Dp
@ Special Thanks:- @Masai School, @Coding Ninjas, @Apna College
